package nz.co.logicons.tlp.core.genericmodels.schemas;



/**
 * Schema for an auto id field (id generated by {@link Datastore#generateId()}).
 * Field is the primary key for document.
 * @author bhambr
 *
 */
public class AutoIdSchema
    extends StringSchema
{
 
}
