package nz.co.logicons.tlp.core.genericmodels.schemas;

import nz.co.logicons.tlp.core.genericmodels.validators.RequiredValidator;
import nz.co.logicons.tlp.core.mongo.MongoDatastore;

/**
 * Schema for a sequence field (id generated by {@link SequenceOperation#nextSequenceDocument(String)}).
 * Not used as a primary key. Is unique (provided no one has imported crap data).
 * @author bhambr
 *
 */
public class SequenceSchema
    extends NumberSchema
{
  
  /** id of sequence. Format is [schemaid].[fieldid]. */
  private String sequenceid;
  
  @Override
  public void init(DocumentSchema documentSchema, MongoDatastore datastore)
  {
    super.init(documentSchema, datastore);
    this.sequenceid = documentSchema.getId() + "." + getId();
    addValidator(new RequiredValidator<>());
  }
  
  public String getSequenceid()
  {
    return sequenceid;
  }

}
