package nz.co.logicons.tlp.core.genericmodels.schemas;

import nz.co.logicons.tlp.core.dbsync.model.FieldTypeAndLength;
import nz.co.logicons.tlp.core.enums.DBType;
import nz.co.logicons.tlp.core.enums.FieldType;
import nz.co.logicons.tlp.core.mongo.MongoDatastore;


/**
 * Schema for a sequence id field (id generated by {@link SequenceOperation#nextSequenceDocument(String)}).
 * Field is the primary key for document.
 * @author bhambr
 *
 */
public class SequenceIdSchema
    extends SequenceSchema
{
  /** id of sequence. Format is [schemaid].[fieldid]. */
  private  String sequenceid;
  

  @Override
  public void init(DocumentSchema documentSchema, MongoDatastore datastore)
  {
    super.init(documentSchema, datastore);
    this.sequenceid = documentSchema.getId() + "." + getId();
  }
  
  public String getSequenceid()
  {
    return sequenceid;
  }
  
  @Override
  public FieldTypeAndLength getFieldTypeAndLength(DBType dbType)
  {
    return new FieldTypeAndLength(FieldType.VARCHAR, 64);
  }

}
